### ISSUE TITLE
CompleteParameter fails and crashes when completing a destructing call in JS

### ISSUE THREAD

**Issue by danihodovic** [tenfyzhong/CompleteParameter.vim#12]
# Issue Prelude
**Please complete these steps and check these boxes (by putting an `x` inside 
the brackets) _before_ filing you issue:**

- [X] I have read and understood CompleteParameter's [README][readme], 
  **especially the [Frequently Asked Questions][faq] section.**
- [X] I have searched CompleteParameters's issue tracker to find issues similar 
  to the one I'm about to report and couldn't find an answer to my problem. 
- [X] If filing a bug report, I have included the output of `vim --version`.
- [X] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [ ] If filing a bug report, I have attached the contents of log follow the steps.
  1. Execute `let g:complete_parameter_log_level = 1`.
  1. Replay you action.
  1. Execute `messages`.
  1. Copy the output and place it to next section. 
- [X] If filing a bug report, I have included a minimal test case that reproduces
  my issue, including what I expected to happen and what actually happened.
- [X] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

Thank you for adhering to this process! It ensures your issue is resolved
quickly and that neither your nor our time is needlessly wasted.

# Issue Details

https://asciinema.org/a/h4mpyMBn180t0VEr5UyZCJPpX

I'm trying to complete a Javascript function which uses destructuring in it's signature. I'm using YouCompleteMe which is backed by Tern under the hood.

```
const object = {
  fn: function ({arg1, arg2, arg3}) {}
}

object.fn(
```

Two problems happen:

- One the first argument insertion CompleteParameter.vim overwrites the opening square bracket. Instead it should only overwrite the first property (`arg1`) of the object.
- When jumping to the last argument Neovim crashes.

# Diagnostic data

## Language

Javascript

## Output of `vim --version`

```
$ nvim --version
Alias tip: v --version
NVIM v0.2.1-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-KAEFpM/neovim-0.2.0ubuntu1+git201705081829+3414+24~ubuntu16.04.1/build/config -I/build/neovim-KAEFpM/neovim-0.2.0ubuntu1+git201705081829+3414+24~ubuntu16.04.1/src -I/build/neovim-KAEFpM/neovim-0.2.0ubuntu1+git201705081829+3414+24~ubuntu16.04.1/.deps/usr/include -I/build/neovim-KAEFpM/neovim-0.2.0ubuntu1+git201705081829+3414+24~ubuntu16.04.1/.deps/usr/include -I/build/neovim-KAEFpM/neovim-0.2.0ubuntu1+git201705081829+3414+24~ubuntu16.04.1/.deps/usr/include -I/build/neovim-KAEFpM/neovim-0.2.0ubuntu1+git201705081829+3414+24~ubuntu16.04.1/.deps/usr/include -I/build/neovim-KAEFpM/neovim-0.2.0ubuntu1+git201705081829+3414+24~ubuntu16.04.1/.deps/usr/include -I/build/neovim-KAEFpM/neovim-0.2.0ubuntu1+git201705081829+3414+24~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-KAEFpM/neovim-0.2.0ubuntu1+git201705081829+3414+24~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-KAEFpM/neovim-0.2.0ubuntu1+git201705081829+3414+24~ubuntu16.04.1/build/include
Compiled by root@lgw01-09

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

## Output of `message`

No output as neovim crashes before then.

## OS version, distribution, etc.

```
$ uname -a
Linux dani-T440s 4.10.0-22-generic #24-Ubuntu SMP Mon May 22 17:43:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

[gist]: https://gist.github.com/
[readme]: https://github.com/tenfyzhong/CompleteParameter.vim/blob/master/README.md
[faq]: https://github.com/tenfyzhong/CompleteParameter.vim/blob/master/README.md#faq

**Comment by tenfyzhong** [comment]
I think it's a good idea to select the whole bracket `{arg1, arg2, arg3}`, but not `arg1`. In the `fn` function, the whole bracket is a parameter, no three. I will fix this later.   
But my nvim doesn't crash.

**Comment by tenfyzhong** [comment]
@danihodovic 1e07ec5 this commit has fixed the issue. btw, I have change the default mapping from `<m-n>`/`<m-p>` to `<c-j>`/`<c-k>` and disable the normal mapping in this branch.

**Comment by danihodovic** [comment]
> @danihodovic 1e07ec5 this commit has fixed the issue. btw, I have change the default mapping from <m-n>/<m-p> to <c-j>/<c-k> and disable the normal mapping in this branch.

Cool! 

So now it will visually select the whole object as an argument? Is this configurable? Ideally I would like to select the first property of the object and go on from there.

**Comment by tenfyzhong** [comment]
It does't support now. I will support it as soon as possible.

**Comment by tenfyzhong** [comment]
@danihodovic I have support this feature and #13 
https://asciinema.org/a/sLWsy01qkg5yigqJblXHClkrn

Example:
fn({a, b}, c)
1. After completion, It will select `{a, b}`
2. goto next, it will select `a`
3. goto next, it will select `b`
4. goto next, it will select `c`

Can you help me to test if #13 fixed or not? I don't know how to test it. 


btw: I have remote all default mapping, you should add this to you vimrc:
https://github.com/tenfyzhong/CompleteParameter.vim#minimal-setting
```viml
inoremap <silent><expr> ( complete_parameter#pre_complete("()")
smap <c-j> <Plug>(complete_parameter#goto_next_parameter)
imap <c-j> <Plug>(complete_parameter#goto_next_parameter)
smap <c-k> <Plug>(complete_parameter#goto_previous_parameter)
imap <c-k> <Plug>(complete_parameter#goto_previous_parameter)
```

**Comment by danihodovic** [comment]
It's fixed. You're a hero @tenfyzhong!

One minor nit: when completing a function where an object is passed in, the completer does not jump between individual properties. Instead it deletes the whole object.

https://asciinema.org/a/cEUr9HpfkgMQlEZA8lDTAFZvP

**Comment by tenfyzhong** [comment]
You need to type `<c-j>` to select `a`.

**Comment by danihodovic** [comment]
I mapped it to `<C-n>` and `<C-m>`.

**Comment by tenfyzhong** [comment]
Can you give me a minial configuration? 
secondary, what's this command `:smap <c-m>` output?

**Comment by danihodovic** [comment]
```
inoremap <silent><expr> ( complete_parameter#pre_complete("()")
imap <c-m> <Plug>(complete_parameter#goto_next_parameter)
smap <c-m> <Plug>(complete_parameter#goto_next_parameter)
imap <c-n> <Plug>(complete_parameter#goto_previous_parameter)
smap <c-n> <Plug>(complete_parameter#goto_previous_parameter)
```

Mapping of `<C-m>`

```
s  <CR>          <Plug>(complete_parameter#goto_next_parameter)
```

**Comment by tenfyzhong** [comment]
https://asciinema.org/a/EViXQdhhWzjiMiYEgVHvU4Ql4
It's ok in my computer. And I found `<c-m>` is equal to `<enter>`. 
Please try to map to other keys and take a test.
