### ISSUE TITLE
Show default value of parameters (if any)

### ISSUE THREAD

**Issue by phcerdan** [tenfyzhong/CompleteParameter.vim#17]
# Issue Prelude

- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim
- Language
    - [ ] C
    - [ ] C++
    - [ ] go
    - [x] python
    - [ ] rust
    - [ ] javascript
    - [ ] typescript
    - [ ] erlang

I think it would be better to show which parameters have a default value, so they are not required, for example in python:

```python
import os
os.getenv(key, default)
```

it would be better to show:
```
os.getenv(key, default=None)
```

**Comment by tenfyzhong** [comment]
I will support this feature this weekend.
