### ISSUE TITLE
Complete info wrong using python

### ISSUE THREAD

**Issue by qrsforever** [tenfyzhong/CompleteParameter.vim#18]
```
#!/usr/bin/python3                                                                                                       
# -*- coding: utf-8 -*-

import os
os.mkdir(Create a directory.If dir_fd is not None, it should be a file descriptor open to a directory, and path should be
        relative; path will then be relative to that directory.dir_fd may not be implemented on your platform. If it is
        unavailable, using it will raise a NotImplementedError.The mode argument is ignored on Windows.)
```                                                                                                                         

when input os.mkdir(, get wrong info: Create a directory.I....

log:
TRACE:1505407984686285: {'word': 'mkdir', 'menu': 'def mkdir', 'info': 'Create a directory.^@^@If dir_fd is not None, it should be a file descriptor open to a directory,^@  and path should be
 relative; path will then be relative to that directory.^@dir_fd may not be implemented on your platform.^@  If it is unavailable, using it will raise a NotImplementedError.^@^@The mode argum
ent is ignored on Windows.', 'kind': '', 'abbr': ''}

**Comment by tenfyzhong** [comment]
Which completion engine you are using?

**Comment by qrsforever** [comment]
YCM

**Comment by tenfyzhong** [comment]
It works well in my computer. Here's a screenshot: https://asciinema.org/a/e1evr0lRF9HHRrMRsmB5PMT5B 

Please update your ycm and test it again.

**Comment by tenfyzhong** [comment]
I have reproduce the bug. I will fix it later.
