### ISSUE TITLE
extra letter after complete

### ISSUE THREAD

**Issue by ZSaberLv0** [tenfyzhong/CompleteParameter.vim#24]
# Issue Prelude

- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [x] Neovim
- Language
    - [ ] C
    - [x] C++
    - [ ] go
    - [ ] python
    - [ ] rust
    - [ ] javascript
    - [ ] typescript
    - [ ] erlang

# Completion Engine and Commit SHA

YouCompleteMe: HEAD

# Minimal Configuration
```
function! CompleteParamFix()
    call feedkeys("\<c-y>", 't')
    return complete_parameter#pre_complete('')
endfunction
inoremap <silent><expr> <cr> pumvisible() ? CompleteParamFix() : "\<c-g>u\<cr>"
```

# Issue Details
* What did you do?
> try complete this code arround `p->f1()`, using `<cr>`
```
class MyClass {
public:
    virtual void f0(int n0, int n1) {}
    virtual int f1(void) {}
};
void main(void) {
    MyClass *p = new MyClass();
    p->f0(p->f1(), 0);
}
```

* What did you expect to happend?
> `p->f0(p->f1(), 0);`

* What actually happened?
> `p->f0(p->f1()n, 0);`
extra `n` shows, `n` may be different letter upon different case

# Messages

**Comment by tenfyzhong** [comment]
You can't call `feedkeys` in the `CompleteParamFix` function. The `feedkeys` only works after `complete_parameter#pre_complete` . 

You should use this version. 

```viml
function! CompleteParamFix()
    "call feedkeys("\<c-y>", 't')
    return "\<c-y>" . complete_parameter#pre_complete('')
endfunction
```
