### ISSUE TITLE
咨询下，如何获取参数的？？

### ISSUE THREAD

**Issue by skywind3000** [tenfyzhong/CompleteParameter.vim#28]
一直想给 YouCompleteMe 写个类似
https://github.com/Shougo/echodoc.vim

的插件，请问如何获取当前 v:completed_item 中对应函数的参数信息呢？

**Comment by tenfyzhong** [comment]
补全后，自动就填充那个变量了。我这个插件已经带了echodoc的功能了。

发自我的 iPhone

**Comment by skywind3000** [comment]
了解，主要是仅想要参数提醒，参数补全个人还用不太习惯。多问一句，用 v:completed_item 的话，似乎必须要用户按下 tab 来选择一个补全项，不按的话即便自己完全输入了，也没有对应 v:completed_item 中的原型信息？

**Comment by tenfyzhong** [comment]
对。你help看一下使用方法吧

发自我的 iPhone

**Comment by garraGH** [comment]
请教一下: 补全失败时,默认(),光标有时停在括号里面,有时停在括号后面,这个是配置的问题么?

**Comment by tenfyzhong** [comment]
停在括号外面的，不是补全失败。是函数本来就没有参数，直接社会出括号了。

发自我的 iPhone
