### ISSUE TITLE
插件没有运行

### ISSUE THREAD

**Issue by glepnir** [tenfyzhong/CompleteParameter.vim#38]
# Issue Prelude

- Category
    - [√ ] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [ √] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [ gou] Neovim
- Language
    - [ ] C
    - [ ] C++
    - [ √] go
    - [ ] python
    - [ ] rust
    - [ ] javascript
    - [ ] typescript
    - [ ] erlang

# Completion Engine and Commit SHA

# Minimal Configuration

# Issue Details

# Messages

安装之后照着gif操作并没有出现参数，是因为括号自动补全的原因吗

**Comment by tenfyzhong** [comment]
1. `:scriptnames` 看插件有没有加载
2. 如果已经加载了，`imap (` 看输出有没有映射成CompleteParameter的
3. 如果已经映射，就给一份最小配置出来我看一下

**Comment by glepnir** [comment]
插件加载了，imap有映射，最小配置是init.vim关于参数补全的配置吗。vim新手sry

**Comment by tenfyzhong** [comment]
你去gitter上把上面的运行结果贴一下。
