### ISSUE TITLE
conflict with ultisnips keymap

### ISSUE THREAD

**Issue by ZSaberLv0** [tenfyzhong/CompleteParameter.vim#40]
# Issue Prelude

- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

# Minimal Configuration
for ultisnips:

            Plug 'SirVer/ultisnips'
            let g:UltiSnipsListSnippets = "<c-o>"
            let g:UltiSnipsJumpForwardTrigger = "<c-o>"
            let g:UltiSnipsJumpBackwardTrigger = "<c-u>"

# Issue Details
the `<c-o>` doesn't work for ultisnips,
removing `CompleteParameter.vim/after/plugin/compatible_with_ultisnips.vim` seems solves the issue

**Comment by tenfyzhong** [comment]
Please set `let g:complete_parameter_use_ultisnips_mappings=0`
