### ISSUE TITLE
插件没有正常工作

### ISSUE THREAD

**Issue by nordwind80** [tenfyzhong/CompleteParameter.vim#43]
# Issue Prelude

- Category
    - [x] Question
    - [ ] Bug
    - [ ] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim
- Language
    - [ ] C
    - [ ] C++
    - [ ] go
    - [x] python
    - [ ] rust
    - [ ] javascript
    - [ ] typescript
    - [ ] erlang

# Completion Engine and Commit SHA

YouCompleteMe: 最新版本

# Minimal Configuration
"CompleteParameter
inoremap <silent><expr> ( complete_parameter#pre_complete("()")
let g:complete_parameter_py_keep_value = 1
smap <c-j> <Plug>(complete_parameter#goto_next_parameter)
imap <c-j> <Plug>(complete_parameter#goto_next_parameter)
smap <c-k> <Plug>(complete_parameter#goto_previous_parameter)
imap <c-k> <Plug>(complete_parameter#goto_previous_parameter

# Issue Details
YCM 自动补全跳转都正常，但是自动补全后按 ( 键 CompleteParameter 没有输出。
另外，CompleteParameter 和 'jiangmiao/auto-pairs' 冲突。禁用后映射正常，但无参数补全。
Python3.7
Vim 8.1.0500

# Messages
[CompleteParameter][09:20:02][TRACE][1542072002977647] s:completed_word: mkdir
[CompleteParameter][09:20:02][TRACE][1542072002977647] select_complete_word: mkdir
[CompleteParameter][09:20:02][TRACE][1542072002977647] {'word': 'mkdir', 'menu': 'def mkdir', 'user_data': '0', 'info': 'Create a directory.^@^@If dir_fd is not None, it should be a file desc
riptor open to a directory,^@  and path should be relative; path will then be relative to that directory.^@dir_fd may not be implemented on your platform.^@  If it is unavailable, using it wi
ll raise a NotImplementedError.^@^@The mode argument is ignored on Windows.', 'kind': 'f', 'abbr': ''}
[CompleteParameter][09:20:02][DEBUG][1542072002977647] ['()']
[CompleteParameter][09:20:02][TRACE][1542072002977647] content:[os.mkdir] current_col:8, left:[os.mkdir], right:[]
[CompleteParameter][09:20:02][TRACE][1542072002977647] content: os.mkdir()
[CompleteParameter][09:20:02][TRACE][1542072002977647] current_col: 8
[CompleteParameter][09:20:02][TRACE][1542072002977647] content:[os.mkdir()],current_col:9,word_begin:10,word_end:10
[CompleteParameter][09:20:02][TRACE][1542072002977647] word_len:0
[CompleteParameter][09:20:02][TRACE][1542072002977647] keys: ()^[^[08la<80>kr"Plug

**Comment by tenfyzhong** [comment]
参照：https://github.com/tenfyzhong/CompleteParameter.vim#cant-work-with-plugin-auto-pairs-use-the-default-mapping-
