### ISSUE TITLE
Arguments Not Shown For Unkown Reason

### ISSUE THREAD

**Issue by weilbith** [tenfyzhong/CompleteParameter.vim#44]
# Issue Prelude
- Category
    - [X] Question
    - [X] Bug
    - [ ] Suggestion
- OS
    - [X] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [X] Neovim
- Language
    - [ ] C
    - [ ] C++
    - [ ] go
    - [X] python
    - [ ] rust
    - [ ] javascript
    - [ ] typescript
    - [ ] erlang

# Completion Engine and Commit SHA
Deoplete.nvim: a5ac69adb4ca5fae12e2f07a07c934213248779a
Deoplete-jedi: 583ee29a0a0fe6206f3f106b8866ff2b663fde74

# Minimal Configuration
```vim
let g:complete_parameter_log_level = 0

imap <expr> (
            \ pumvisible() ?
            \ complete_parameter#pre_complete('()') :
            \ "\<Plug>delimitMate("

nmap <C-l> <Plug>(complete_parameter#goto_next_parameter)
imap <C-l> <Plug>(complete_parameter#goto_next_parameter)

nmap <C-h> <Plug>(complete_parameter#goto_previous_parameter)
imap <C-h> <Plug>(complete_parameter#goto_previous_parameter)
```

# Issue Details
I try to get this plugin working. As in #37 I'm also using _DelimitMate_. Therefore I took the presented solution with the `<expr>` mapping. I can confirm, that this mapping is active with `imap (`. The expression work as expected, but I get no arguments. If I try to jump to the next or previous argument also the logging output appears without any effect. 
The code I use as example is a `example.py`:

```python
def my_example_function(a, b):
    return a + b

test = my_example_funct...
```

Please ask if you need any more information. I rly rly like to use this plugin!

# Messages
```vim
[CompleteParameter][14:51:34][TRACE][732004105] s:completed_word:
[CompleteParameter][14:51:34][TRACE][732004105] select_complete_word: my_example_funct
[CompleteParameter][14:51:34][TRACE][732004105] ^P()<80>kl
match 2 of 2
[CompleteParameter][14:51:37][TRACE][3490999488] content:[test = my_example_function()],current_col:27,word_begin:28,word_end:28
[CompleteParameter][14:51:37][TRACE][3490999488] word_len:0
[CompleteParameter][14:51:38][TRACE][4400979381] content:[test = my_example_function()],current_col:28,word_begin:27,word_end:27
[CompleteParameter][14:51:38][TRACE][4400979381] word_len:0
```

**Comment by tenfyzhong** [comment]
I use your configuration, but I work well. My log:
```
[CompleteParameter][10:20:41][TRACE][411878900931] {'word': 'my_example_function', 'menu': '[jedi] ', 'user_data': '', 'info': 'my_example_function(a, b)', 'kind': 'function', 'abbr': 'my_example_function(a, b)'}
[CompleteParameter][10:20:41][DEBUG][411878900931] ['(a, b)']
[CompleteParameter][10:20:41][TRACE][411878900931] content:[test = my_example_function] current_col:26, left:[test = my_example_function], right:[]
[CompleteParameter][10:20:41][TRACE][411878900931] content: test = my_example_function(a, b)
[CompleteParameter][10:20:41][TRACE][411878900931] current_col: 26
[CompleteParameter][10:20:41][TRACE][411878900931] content:[test = my_example_function(a, b)],current_col:27,word_begin:28,word_end:29
[CompleteParameter][10:20:41][TRACE][411878900931] word_len:1
[CompleteParameter][10:20:41][TRACE][411878900931] keys: (a, b)^[^[026llv^G
```
You should select the complete item first and then type `(`. 
![image](https://user-images.githubusercontent.com/5044825/50128174-f0430580-02ae-11e9-934d-d212f533ca40.png)

**Comment by weilbith** [comment]
That is weird. I am selecting the correct entry and then typing `(`. I always end up with `my_example_function(()`...
What would I need for a minimal testable environment? :thinking:

**Comment by weilbith** [comment]
Can we talk about supporting an alternative way for completion?
I've already implemented a quick first solution on a [fork](https://github.com/weilbith/CompleteParameter.vim), but I would like to turn it into a mature PR so I don't rely on a fork I've to maintain.
I've came to this solution while I was working on making [Ultisnips](https://github.com/SirVer/ultisnips) working as well.

The idea:
There are some plugins which work in combination with the completion of items. Also if _Ultisnips_ works also standalone without an external completion engine, its handsome to do so. So in my opinion both plugins have something in common: do something with the completed item.
So instead of tweak the mappings for the selection of a suggested item from the pop-up menu up to unreadable expressions for each new such plugin or adding new mappings which also selects, but with different result, I suppose to decouple them.
So the first step is that such plugins enrich the completion item list, if needed. The whole rest of completion interaction with the user should be not handled by the plugin in any way. So it is straight forward for the user to configure and use.
After an item has been completed, the plugins can be added to work an this object again. Completion items can have a bunch of properties, more than displayed. At least the `uder_data` field opens a lot of options. But stick to the commonly defined ones, the `kind` property is most-likely what we need. So after completion, depending on the type of the completed item, different plugins can be called to handle them.

My current setup does this for _Ultisnips_ and _CompleteParameter_ now. The basic structure (just compressed as showcase) looks like this:

```vim
autocmd! CompleteDone * call <SID>execute_completion_hooks()

function! execute_completion_hooks() abort
  " Ignore events without completion item.
  if empty(v:completed_item) | return | endif

  " Call hook depending on the completion items kind property.

  " Extend snippets.
  if v:completed_item.kind ==# 'snippet'
    call UltiSnips#ExpandSnippet()
  endif

  " Complete function parameter.
  if v:completed_item.kind ==# 'f' || v:completed_item.kind ==# 'function'
    call feedkeys(cmp#pre_complete('()'))
  endif
endfunction
```

I have an open PR SirVer/ultisnips#1043 to make this possible for _Ultisnips_, where the `kind` property is not set for completion items. (see [this comment](https://github.com/SirVer/ultisnips/issues/376#issuecomment-449409513) for a dirty solution without PR). In contrast to many other solutions this makes it possible to have no additional mapping, but does not expand each trigger which has the same name as a possible variable name or function the completion engine suggest as well. It should be only expanded, if the user selects the pop-up menu entry with the snippet!
For _CompleteParameter_ only the `cmp#pre_complete` function must be adjusted. Cause in this scenario the PUM is not visible anymore, the [check](https://github.com/tenfyzhong/CompleteParameter.vim/blob/04310b244c36d170bfe19d95e401f74d97a61453/autoload/cmp.vim#L131) fails always. I've added a configurable variable to enable the event based completion. To preserve the current behavior this is disabled per default of cause. 

The question is what do you think about this? And if you are fine with such an alternative to the mappings, we have to define how the solution should look like. At least the documentation must be extended, but maybe this evolves to a much better result, instead of setting a hacky option.
Thanks for reading!

**Comment by weilbith** [comment]
Closing, since the actual problem is solved.
