### ISSUE TITLE
Hope to support coc.nvim

### ISSUE THREAD

**Issue by bbxytl** [tenfyzhong/CompleteParameter.vim#46]
# Issue Prelude

- Category
    - [ ] Question
    - [ ] Bug
    - [x] Suggestion
- OS
    - [ ] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim
- Language
    - [ ] C
    - [ ] C++
    - [x] go
    - [ ] python
    - [ ] rust
    - [ ] javascript
    - [ ] typescript
    - [ ] erlang

# Completion Engine and Commit SHA

# Minimal Configuration

# Issue Details

最近换了 coc.nvim，发现补全时的参数补全没有了，查了下发现这里好像没有支持 coc.nvim，所以我是来向大佬请求支持 coc.nvim 的参数补全的。。。。。

# Messages

**Comment by tenfyzhong** [comment]
coc.nvim自带了参数补全啊。直接用它自带的就好。

**Comment by bbxytl** [comment]
coc.nvim 的参数补全是浮窗，没有你这个好用，直接补默认的

**Comment by tenfyzhong** [comment]
它应该是可以配的，可以看一下文档

发自我的 iPhone
