### ISSUE TITLE
Python doesn't work.

### ISSUE THREAD

**Issue by josefson** [tenfyzhong/CompleteParameter.vim#5]
Despite what the readme says, i tried it with python files and it didn't work.
I even removed all my config files and installed only YCM and CompleteParameter in order to see if my config was somewhat problematic, but it didn't work this way either.

**Comment by tenfyzhong** [comment]
There are a bug on different version python. Please pull the newest code to try again. If it still can't work. Please show me the messege below: 
## python version
> the output of `python --version`

## vim version
> the output of `vim --version`

## the log of CompleteParameter
> get the log follow the steps:
> 1. Execute `let g:complete_parameter_log_level = 1` in vim. 
> 2. Replay you action.
> 3. Execute `messages`

**Comment by tenfyzhong** [comment]
@josefson  can it work now?
