### ISSUE TITLE
keymaping issue

### ISSUE THREAD

**Issue by tracyone** [tenfyzhong/CompleteParameter.vim#6]
```
 let g:complete_parameter_mapping_goto_next = '<c-j>'
  let g:complete_parameter_mapping_goto_previous = '<c-k>'

```

this will change the keymaping in normal mode????why?

**Comment by tenfyzhong** [comment]
If the value of `g:complete_parameter_mapping_goto_next`/`g:complete_parameter_mapping_goto_previous` is empty,   I will use the default value `<m-n>`/`<m-p>`. And then map them in the normal, insert ,select, visual mode. It will map in the normal mode too. It'll easy to jump to the next parameter when you are in the normal mode.

**Comment by tracyone** [comment]
好吧，还是说中文吧。

更新了。

不是空的。

我的意思是为啥我这样映射之后，ctrl-j和ctrl-k在一般模式下原来的映射也丢失了？

**Comment by tenfyzhong** [comment]
当前使用了noremap的方式映射了普通模式、插入模式、选择模式、可视模式。所以普通模式下也是跳到下一个参数了。我提供一个配置来设置可以产生作用的模式吧。

**Comment by tenfyzhong** [comment]
@tracyone 这个提交[189ae08](https://github.com/tenfyzhong/CompleteParameter.vim/commit/189ae08937c855f15c665b1ce74a5f9ecfbd8471) 已经支持对某些模式下才进行mapping，也可以直接checkout到develop分支。
增加了四个配置：
`g:complete_parameter_goto_next_mode`,`g:complete_parameter_goto_previous_mode`,`g:complete_parameter_mapping_overload_down_mode`,`g:complete_parameter_mapping_overload_up_mode`。给前两个设置值为`iv`就可以解决你的总是了。
```viml
let g:complete_parameter_goto_next_mode = 'iv'
let g:complete_parameter_goto_previous_mode = 'iv'
```
